#ifndef EVENT_TYPES_H
#define EVENT_TYPES_H

#pragma once
#include <cstdint>

#include "SyncedObjects.h"

// TODO: Implement union for EventTypes for easier event type handling

enum class EventType : uint8_t {

// System Events
    SYSTEM_STARTUP,
    SYSTEM_SHUTDOWN,
    SYSTEM_RESTART,
    KILL_PILOT,
    FLIGHT_TIME_START_SET_TRUE,
    FLIGHT_TIME_START_SET_FALSE,
    FLIGHT_TIME_END_SET_TRUE,
    FLIGHT_TIME_END_SET_FALSE,
    FLIGHT_START_TRUE,
    FLIGHT_START_FALSE,

// Control Mode Events
    CONTROL_MODE_CHANGE_AUTO,
    CONTROL_MODE_CHANGE_ASSIST,
    CONTROL_MODE_CHANGE_MANUAL,
    CONTROL_MODE_CHANGE_HOLDING,
    CONTROL_MODE_CHANGE_TAXI,
    CONTROL_MODE_CHANGE_EMERGENCY,
    CONTROL_MODE_CHANGE_RECOVERY,
    CONTROL_MODE_CHANGE_PAIRING,
    // Control Mode Accept
    CONTROL_MODE_CHANGE_AUTO_ACCEPT,
    CONTROL_MODE_CHANGE_ASSIST_ACCEPT,
    CONTROL_MODE_CHANGE_MANUAL_ACCEPT,
    CONTROL_MODE_CHANGE_HOLDING_ACCEPT,
    CONTROL_MODE_CHANGE_TAXI_ACCEPT,
    CONTROL_MODE_CHANGE_EMERGENCY_ACCEPT,
    CONTROL_MODE_CHANGE_RECOVERY_ACCEPT,
    CONTROL_MODE_CHANGE_PAIRING_ACCEPT,
    


    
// Airplane Status Events
    AIRPLANE_CONNECTED_TRUE,
    AIRPLANE_CONNECTED_FALSE,

    PAIRED_FALSE,
    PAIRED_TRUE,
    PAIRED_FAIL,

    THROTTLE_LOCK_DATA_CHANGE,
    THROTTLE_LOCK_FALSE,
    THROTTLE_LOCK_TRUE,

    WITHIN_RANGE_FALSE,
    WITHIN_RANGE_TRUE,

    APPROACHING_BOUNDARY_FALSE,
    APPROACHING_BOUNDARY_TRUE,

    RETURNING_HOME_FALSE,
    RETURNING_HOME_TRUE,

    IS_FLYING_FALSE,
    IS_FLYING_TRUE,

    AIRPLANE_GPS_ACTIVE_FALSE,
    AIRPLANE_GPS_ACTIVE_TRUE,
    AIRPLANE_GPS_FAIL_FALSE,
    AIRPLANE_GPS_FAIL_TRUE,

    ATC_GPS_ACTIVE_FALSE,
    ATC_GPS_ACTIVE_TRUE,
    ATC_GPS_FAIL_FALSE,
    ATC_GPS_FAIL_TRUE,

    IMU_ACTIVE_FALSE,
    IMU_ACTIVE_TRUE,
    IMU_FAIL_FALSE,
    IMU_FAIL_TRUE,

    FIXED_ALTITUDE_DATA_CHANGE,
    FIXED_ALTITUDE_FALSE,
    FIXED_ALTITUDE_TRUE,

    FIXED_HEADING_DATA_CHANGE,
    FIXED_HEADING_FALSE,
    FIXED_HEADING_TRUE,

    FIXED_SPEED_DATA_CHANGE,
    FIXED_SPEED_FALSE,
    FIXED_SPEED_TRUE,

    FIXED_HEADING_DATA_CHANGE,
    FIXED_HEADING_FALSE,
    FIXED_HEADING_TRUE,

    FIXED_SPEED_DATA_CHANGE,
    FIXED_SPEED_FALSE,
    FIXED_SPEED_TRUE,

// Airplane Events
    ENGINE_ON_TRUE,
    ENGINE_ON_FALSE,
    ENGINE_FAIL_FALSE,
    ENGINE_FAIL_TRUE,


// Flight Events

    ALTITUDE_GROUND,
    ALTITUDE_OK,
    ALTITUDE_WARNING_LOW,
    ALTITUDE_LOW,
    ALTITUDE_HIGH,
    ALTITUDE_WARNING_HIGH,

    PITCH_GROUND,
    PITCH_OK,
    PITCH_WARNING_LOW,
    PITCH_LOW,
    PITCH_HIGH,
    PITCH_WARNING_HIGH,

    ROLL_OK,
    ROLL_LEFT_LOW,
    ROLL_LEFT_MID,
    ROLL_LEFT_HIGH,
    ROLL_LEFT_WARNING,
    ROLL_LEFT_DANGER,
    ROLL_RIGHT_LOW,
    ROLL_RIGHT_MID,
    ROLL_RIGHT_HIGH,
    ROLL_RIGHT_WARNING,
    ROLL_RIGHT_DANGER,

    AIR_SPEED_GROUND,
    AIR_SPEED_OK,
    AIR_SPEED_WARNING_LOW,
    AIR_SPEED_LOW,
    AIR_SPEED_HIGH,
    AIR_SPEED_WARNING_HIGH,

    ENGINE_STALL_FALSE,
    ENGINE_STALL_TRUE,

    MOTOR_SPINNING_TRUE,
    MOTOR_SPINNING_FALSE,


// Flight Plan Events
    WAYPOINT_SET_FALSE,
    WAYPOINT_SET_TRUE,
    WAYPOINT_ENROUTE_TRUE,
    WAYPOINT_ENROUTE_FALSE,
    WAYPOINT_CIRCLE,
    WAYPOINT_DATA_UPDATE,

// Flight Phase Events
    FLIGHT_PHASE_CHANGE_NONE,
    FLIGHT_PHASE_CHANGE_INIT,
    FLIGHT_PHASE_CHANGE_TAXI_TO_RUNWAY,
    FLIGHT_PHASE_CHANGE_PREFLIGHT_CHECKS,
    FLIGHT_PHASE_CHANGE_TAKEOFF_ROLL,
    FLIGHT_PHASE_CHANGE_TAKEOFF_ASCEND,
    FLIGHT_PHASE_CHANGE_CLIMB,
    FLIGHT_PHASE_CHANGE_CRUISE,
    FLIGHT_PHASE_CHANGE_DESCENT,
    FLIGHT_PHASE_CHANGE_ALIGN_APPROACH,
    FLIGHT_PHASE_CHANGE_FINAL_APPROACH,
    FLIGHT_PHASE_CHANGE_FLARE,
    FLIGHT_PHASE_CHANGE_TOUCHDOWN,
    FLIGHT_PHASE_CHANGE_ROLL_OUT,
    FLIGHT_PHASE_CHANGE_GO_AROUND,
    FLIGHT_PHASE_CHANGE_HOLDING_PATTERN,
    FLIGHT_PHASE_CHANGE_EMERGENCY_LANDING,
    FLIGHT_PHASE_CHANGE_COMPLETE_FLIGHT,

};


    //CONTROL_MODE_CHANGE,
    //PAITED_CHANGE,
    //THROTTLE_LOCK_CHANGE,

#endif // EVENT_TYPES_H