#ifndef SYNCEDOBJECTS_H
#define SYNCEDOBJECTS_H

/*
enum class SyncedObjects {
    // CONTROL_MODE IS MULTI-BIT
    CONTROL_MODE,
    PAIRED,
    THROTTLE_LOCK,
    WITHIN_RANGE,
    RETURNING_HOME,
    FLYING,
    GPS_ACTIVE,
    FIXED_ALTITUDE,
    FIXED_HEADING,
    FIXED_SPEED,
    FIXED_ALTITUDE_CHANGE,
    FIXED_HEADING_CHANGE,    
    FIXED_SPEED_CHANGE
};
*/


#endif // SYNCEDOBJECTS_H