#ifndef EVENT_TYPES_H
#define EVENT_TYPES_H

#pragma once
#include <cstdint>

#include "SyncedObjects.h"


enum class EventType : uint8_t {

    // Control Mode Events
    CONTROL_MODE_CHANGE_AUTO,
    CONTROL_MODE_CHANGE_ASSIST,
    CONTROL_MODE_CHANGE_MANUAL,
    CONTROL_MODE_CHANGE_HOLDING,
    CONTROL_MODE_CHANGE_TAXI,
    CONTROL_MODE_CHANGE_EMERGENCY,
    CONTROL_MODE_CHANGE_RECOVERY,
    CONTROL_MODE_CHANGE_PAIRING,
    
    // Airplane Status Events
    AIRPLANE_CONNECTED_TRUE,
    AIRPLANE_CONNECTED_FALSE,

    PAIRED_FALSE,
    PAIRED_TRUE,

    THROTTLE_LOCK_FALSE,
    THROTTLE_LOCK_TRUE,

    WITHIN_RANGE_FALSE,
    WITHIN_RANGE_TRUE,

    APPROACHING_BOUNDARY_FALSE,
    APPROACHING_BOUNDARY_TRUE,

    RETURNING_HOME_FALSE,
    RETURNING_HOME_TRUE,

    FLYING_FALSE,
    FLYING_TRUE,

    GPS_ACTIVE_FALSE,
    GPS_ACTIVE_TRUE,

    FIXED_ALTITUDE_DATA_CHANGE,
    FIXED_ALTITUDE_FALSE,
    FIXED_ALTITUDE_TRUE,

    FIXED_HEADING_DATA_CHANGE,
    FIXED_HEADING_FALSE,
    FIXED_HEADING_TRUE,

    FIXED_SPEED_DATA_CHANGE,
    FIXED_SPEED_FALSE,
    FIXED_SPEED_TRUE,

    FIXED_HEADING_DATA_CHANGE,
    FIXED_HEADING_FALSE,
    FIXED_HEADING_TRUE,

    FIXED_SPEED_DATA_CHANGE,
    FIXED_SPEED_FALSE,
    FIXED_SPEED_TRUE,

    // Airplane Events
    ENGINE_ON_TRUE,
    ENGINE_ON_FALSE,


    // Flight Events
    LOW_ALTITUDE,
    HIGH_ALTITUDE,
    LOW_PITCH,
    HIGH_PITCH,
    LOW_SPEED,
    HIGH_SPEED,
    HIGH_LEFT_BANK,
    HIGH_RIGHT_BANK,
    ENGINE_STALL,
    MOTOR_SPINNING_TRUE,
    MOTOR_SPINNING_FALSE,


};


    //CONTROL_MODE_CHANGE,
    //PAITED_CHANGE,
    //THROTTLE_LOCK_CHANGE,

#endif // EVENT_TYPES_H